### ISSUE TITLE
SerializeField error in Unity 6000.3.0f1

### ISSUE THREAD

**Issue by towneh** [dooly123/Basis#426]
### Describe the bug?

`error CS0592: Attribute 'SerializeField' is not valid on this declaration type. It is only valid on 'field' declarations.`

When opening the latest developer in Unity 6000.3.0f1

### Steps to Reproduce

Open the framework in Unity 6000.3.0f1

### The expected behavior

This behaviour changed in Unity 6.3 release as per https://docs.unity3d.com/Manual/UpgradeGuideUnity63.html

> SerializeField attribute restriction to fields
>
>The [SerializeField] attribute has been updated so that you can only apply it to fields. Applying it to properties, methods, types, or other code elements will now result in a compile-time error. This change helps ensure you use the attribute correctly, as it has no effect on non-field members.
>
>Projects already using the attribute correctly will not be affected. Only projects which have misapplied the attribute will have compiler errors.
>
>If you encounter a compile error, you can usually resolve it by removing the attribute from the affected member. If you encounter a compile error because you applied the attribute to an auto-implemented property when you intended to apply [SerializeField] to the backing field of an auto-implemented property, use the [field: SerializeField] syntax to apply it correctly.
>
>For more information, refer to [SerializeField](https://docs.unity3d.com/ScriptReference/SerializeField.html) and [Serialization rules](https://docs.unity3d.com/Manual/script-serialization-rules.html).

### BasisVR Release Version

n/a

### Log Files

n/a

**Comment by towneh** [comment]
Alright, alright, fixed 10 hours ago in https://github.com/BasisVR/Basis/commit/b3f55bd200571f944eeeed7582435e5cc9b4d547 and here I was about to scuff it with [field: SerializeField]
